version: '3.9'

services:
  web:
    container_name: backend
    image: backend
    build:
      context: .
    ports:
      - 3000:3000
    env_file:
      - .env

  db:
    container_name: db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
